# Ejemplo de render.yaml

env:
  - key: DJANGO_SETTINGS_MODULE
    value: "ServerJuego.settings.production"

buildCommand: "pip install -r requirements.txt"
startCommand: "gunicorn ServerJuego.wsgi:application --bind 0.0.0.0:$PORT"
